version: "3.5"
services:
  pipeline:
    build: pipeline/
    image: rappi/pipeline
    command: python run_pipeline.py
    volumes:
      - ./pipeline/:/pipeline/
      - ./data/:/data/
      - ./artifacts/:/artifacts/

  api:
    build: .
    volumes:
      - ./api/:/api/
      - ./pipeline/:/pipeline/
      - ./data/:/data/
      - ./artifacts/:/artifacts/
    ports:
      - 5000:5000
